services:
  app:
    container_name: eaipago-be
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - redis
      - fakes3

  redis:
    container_name: redis
    image: redis:8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  fakes3:
    container_name: fakes3
    image: lphoward/fake-s3
    ports:
      - 4569:4569
    command: -r /fakes3_root -p 4569
    volumes:
      - fakes3_root:/fakes3_root

volumes:
  redis_data:
  fakes3_root:
